# render.yaml
services:
  - type: web
    name: ai-content-generator-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYO3_USE_ABI3_FORWARD_COMPATIBILITY
        value: "1"
